"""empty message

Revision ID: 36806f591078
Revises: None
Create Date: 2016-11-13 22:54:32.441736

"""

# revision identifiers, used by Alembic.
revision = '36806f591078'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatchers',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requesters',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.Column('dispatcher_id', models.core_models.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['dispatchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storages',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('dispatcher_id', models.core_models.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['dispatchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('job_id', models.core_models.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.Column('dispatcher_id', models.core_models.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['dispatchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', models.core_models.GUID(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('space_used_per_unit', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('human_name', sa.String(), nullable=True),
    sa.Column('job_id', models.core_models.GUID(), nullable=True),
    sa.Column('storage_id', models.core_models.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.drop_table('workers')
    op.drop_table('tasks')
    op.drop_table('storages')
    op.drop_table('requesters')
    op.drop_table('results')
    op.drop_table('jobs')
    op.drop_table('dispatchers')
    ### end Alembic commands ###
