"""empty message

Revision ID: c01872b64c6c
Revises: 36806f591078
Create Date: 2016-11-13 22:55:07.350199

"""

# revision identifiers, used by Alembic.
revision = 'c01872b64c6c'
down_revision = '36806f591078'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('result_id', models.core_models.GUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'results', ['result_id'], ['id'])
    op.add_column('results', sa.Column('job_id', models.core_models.GUID(), nullable=True))
    op.create_foreign_key(None, 'results', 'jobs', ['job_id'], ['id'])
    op.add_column('tasks', sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('tasks', 'result')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'steps')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'job_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'result_id')
    ### end Alembic commands ###
